name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint with pre-commit
        uses: pre-commit/action@v2.0.2
