name: pypi

on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Set version
      env:
        GITHUB_TAG: ${{github.ref}}
      run: python scripts/ci_set_version_from_git.py
    - name: Build
      run: python setup.py sdist bdist_wheel
    - name: Assert version
      env:
        GITHUB_TAG: ${{github.ref}}
      run: python scripts/ci_assert_version_from_git.py
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
