name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Tests py${{ matrix.py }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        py:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Run tests
        run: python -m tests
